export const saleProducts = [
  {
    id: "laptop-13",
    name: "Dell Inspiron 16 Plus",
    brand: "Dell",
    price: 119999,
    category: "Laptops",
    image:
      "https://www.amazon.com/Dell-Inspiron-Plus-7640-Laptop/dp/B0D273XDFY",
    rating: 4.4,
    stock: 17,
  },
  {
    id: "laptop-14",
    name: "HP Omen 16",
    brand: "HP",
    price: 124999,
    category: "Laptops",
    image: "https://www.hp.com/us-en/gaming-pc/laptops/2023-omen-16-intel.html",
    rating: 4.5,
    stock: 11,
  },
  {
    id: "laptop-15",
    name: "Asus ZenBook 14",
    brand: "Asus",
    price: 109999,
    category: "Laptops",
    image:
      "https://www.asus.com/us/laptops/for-home/zenbook/asus-zenbook-14-ux3405/",
    rating: 4.6,
    stock: 14,
  },
  {
    id: "phone-14",
    name: "Motorola Edge 40",
    brand: "Motorola",
    price: 39999,
    category: "Smartphones",
    image: "https://www.motorola.com/us/smartphones/motorola-edge-40/p",
    rating: 4.1,
    stock: 12,
  },
  {
    id: "phone-15",
    name: "Asus ROG Phone 7",
    brand: "Asus",
    price: 79999,
    category: "Smartphones",
    image: "https://rog.asus.com/phones/rog-phone-7/",
    rating: 4.6,
    stock: 10,
  },
  {
    id: "watch-14",
    name: "Fitbit Sense",
    brand: "Fitbit",
    price: 17999,
    category: "Smartwatches",
    image: "https://store.google.com/us/product/fitbit_sense_2?hl=en-US",
    rating: 4.4,
    stock: 18,
  },
  {
    id: "watch-16",
    name: "Garmin Venu 2",
    brand: "Garmin",
    price: 25999,
    category: "Smartwatches",
    image: "https://www.garmin.com/en-US/p/707538/",
    rating: 4.5,
    stock: 15,
  },
];
